Resolve merge conflict in dynamic_markdown.py

diff --git a/.github/workflows/test_cli.yaml b/.github/workflows/test_cli.yaml
--- a/.github/workflows/test_cli.yaml
+++ b/.github/workflows/test_cli.yaml
@@ -5,6 +5,9 @@ on:
     branches: [main]
   pull_request:
 
+permissions:
+  contents: read
+
 env:
   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
   TURBO_TEAM: marimo
@@ -21,8 +24,8 @@ jobs:
         with:
           filters: |
             cli:
-              - '**'
-              - '!{docs/**,examples/**,README.md,tests/**,frontend/**}'
+              - 'marimo/**'
+              - '.github/workflows/test_cli.yaml'
 
   build_wheel:
     needs: changes
@@ -49,14 +52,13 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 22
-          cache: 'pnpm'
-          cache-dependency-path: '**/pnpm-lock.yaml'
+          cache: "pnpm"
+          cache-dependency-path: "**/pnpm-lock.yaml"
 
       - name: 📦 Build frontend
         run: make fe
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-          NODE_OPTIONS: '--max_old_space_size=8192'
 
       - name: 🥚 Install Hatch
         uses: pypa/hatch@install
@@ -101,8 +103,9 @@ jobs:
     timeout-minutes: 10 # 2024-01-18 avg: 2.5m max: 4.5m
     strategy:
       matrix:
-        python-version: ['3.12']
-        os: [ubuntu-latest, macos-latest, windows-latest]
+        python-version: ["3.12"]
+        # TODO: update to latest once networking issues on macos-15 are resolved
+        os: [ubuntu-latest, macos-14, windows-latest]
 
     steps:
       - name: 🛑 Cancel Previous Runs
@@ -110,12 +113,12 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: 🐍 Setup uv
-        uses: astral-sh/setup-uv@v5
-        # Windows is throwing an error with uv on the Post step
-        continue-on-error: ${{ matrix.os == 'windows-latest' }}
+        uses: astral-sh/setup-uv@v7
         with:
           enable-cache: true
           python-version: ${{ matrix.python-version }}
+          # TODO(https://github.com/astral-sh/setup-uv/issues/226): Remove this.
+          prune-cache: ${{ matrix.os != 'windows-latest' }}
 
       - name: Install Python deps
         run: |
@@ -148,7 +151,7 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: 🐍 Setup uv
-        uses: astral-sh/setup-uv@v5
+        uses: astral-sh/setup-uv@v7
         with:
           enable-cache: true
           python-version: 3.12
@@ -162,3 +165,23 @@ jobs:
         run: |
           uv add pytest pytest-asyncio
           uv pip install marimo*whl
+
+      - name: Check example quality with marimo check
+        shell: bash
+        run: |
+          echo "Checking examples directory..."
+          uv run marimo check --ignore-scripts --strict examples/**.py
+
+      - name: Check tutorial quality with marimo check
+        shell: bash
+        run: |
+          echo "Checking tutorials..."
+          uv run marimo check --ignore-scripts --fix \
+            marimo/_tutorials/**.py >> /dev/null \
+            || echo "Errors expected"
+          # Fail if there's a git diff
+          if [[ -n "$(git status --porcelain marimo/_tutorials)" ]]; then
+            echo "marimo check found issues in tutorials."
+            git --no-pager diff marimo/_tutorials
+            exit 1
+          fi
